apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  realtime-classifier
  labels:
    name:  realtime-classifier
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name:  realtime-classifier
    spec:
      containers:
      - image:  graphy/realtime_classifier:1.0.3
        name:  realtime-classifier
        env:
        - name: KAFKA_SERVERS
          value: kafka-0.broker.kafka.svc.cluster.local:9092,kafka-1.broker.kafka.svc.cluster.local:9092
        - name: CASSANDRA_NODES
          value: cassandra-0.cassandra.cassandra.svc.cluster.local,cassandra-1.cassandra.cassandra.svc.cluster.local
      restartPolicy: Always
