apiVersion: batch/v1
kind: Job
metadata:
  name: create-keyspace-job
  namespace: cassandra
spec:
  template:
    metadata:
      name: create-keyspace-job
    spec:
      containers:
      - name: cqlsh
        image: projectepic/cqlsh:1.0.1
        command: ["/bin/sh"]
        args: ["-c", "echo \"CREATE KEYSPACE IF NOT EXISTS graphy WITH replication = { 'class': 'SimpleStrategy', 'replication_factor': '2' }; exit;\" | cqlsh cassandra-0.cassandra --cqlversion=3.4.2"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-table-job
  namespace: cassandra
spec:
  template:
    metadata:
      name: create-table-job
    spec:
      containers:
      - name: cqlsh
        image: projectepic/cqlsh:1.0.1
        command: ["/bin/sh"]
        args: ["-c", "echo \"CREATE TABLE IF NOT EXISTS graphy.tweet (twid bigint,creation_time timestamp,body text, trend text, topic text, user text, location text, PRIMARY KEY (trend,creation_time,twid)) WITH CLUSTERING ORDER BY (creation_time  DESC);exit;\" | cqlsh cassandra-0.cassandra --cqlversion=3.4.2"]
      restartPolicy: Never
