apiVersion: batch/v1
kind: Job
metadata:
  name: alter-table-job
  namespace: cassandra
spec:
  template:
    metadata:
      name: alter-table-job
    spec:
      containers:
      - name: cqlsh
        image: projectepic/cqlsh:1.0.1
        command: ["/bin/sh"]
        args: ["-c", "echo \"ALTER TABLE graphy.tweet ADD sentiment text;exit;\" | cqlsh cassandra-0.cassandra --cqlversion=3.4.2"]
      restartPolicy: Never
